// Auto-generated by Supabase. Do not edit manually.
// Regenerate with: npx supabase gen types typescript --project-id dkbhzfcznwxfumfcaifs
// (or via the Supabase MCP generate_typescript_types tool)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.15'
  }
  public: {
    Tables: {
      external_codes: {
        Row: {
          bound_at: string
          bound_by: string | null
          code_type: Database['public']['Enums']['external_code_type']
          code_value: string
          entity_id: string
          entity_type: Database['public']['Enums']['external_entity_type']
          household_id: string
          id: string
          label: string | null
        }
        Insert: {
          bound_at?: string
          bound_by?: string | null
          code_type?: Database['public']['Enums']['external_code_type']
          code_value: string
          entity_id: string
          entity_type: Database['public']['Enums']['external_entity_type']
          household_id: string
          id?: string
          label?: string | null
        }
        Update: {
          bound_at?: string
          bound_by?: string | null
          code_type?: Database['public']['Enums']['external_code_type']
          code_value?: string
          entity_id?: string
          entity_type?: Database['public']['Enums']['external_entity_type']
          household_id?: string
          id?: string
          label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'external_codes_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
        ]
      }
      household_members: {
        Row: {
          household_id: string
          joined_at: string
          role: Database['public']['Enums']['household_role']
          user_id: string
        }
        Insert: {
          household_id: string
          joined_at?: string
          role?: Database['public']['Enums']['household_role']
          user_id: string
        }
        Update: {
          household_id?: string
          joined_at?: string
          role?: Database['public']['Enums']['household_role']
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'household_members_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
        ]
      }
      households: {
        Row: {
          created_at: string
          id: string
          invite_token: string
          name: string
          owner_id: string
          photo_url: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          invite_token?: string
          name: string
          owner_id: string
          photo_url?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          invite_token?: string
          name?: string
          owner_id?: string
          photo_url?: string | null
        }
        Relationships: []
      }
      item_history: {
        Row: {
          id: string
          item_id: string
          moved_at: string
          moved_by: string | null
          note: string | null
          place_id: string | null
        }
        Insert: {
          id?: string
          item_id: string
          moved_at?: string
          moved_by?: string | null
          note?: string | null
          place_id?: string | null
        }
        Update: {
          id?: string
          item_id?: string
          moved_at?: string
          moved_by?: string | null
          note?: string | null
          place_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'item_history_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_history_place_id_fkey'
            columns: ['place_id']
            isOneToOne: false
            referencedRelation: 'places'
            referencedColumns: ['id']
          },
        ]
      }
      item_placements: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          item_id: string
          note: string | null
          place_id: string
          quantity: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          item_id: string
          note?: string | null
          place_id: string
          quantity?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          item_id?: string
          note?: string | null
          place_id?: string
          quantity?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'item_placements_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_placements_place_id_fkey'
            columns: ['place_id']
            isOneToOne: false
            referencedRelation: 'places'
            referencedColumns: ['id']
          },
        ]
      }
      items: {
        Row: {
          created_at: string
          created_by: string | null
          current_place_id: string | null
          current_place_since: string | null
          description: string | null
          embedding: string | null
          estimated_value: number | null
          household_id: string
          id: string
          last_moved_by: string | null
          metadata: Json
          name: string
          photo_urls: string[]
          product_link: string | null
          product_links: string[]
          qr_token: string | null
          quantity: number
          tags: string[]
          updated_at: string
          value_currency: string | null
          value_source: string | null
          value_updated_at: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          current_place_id?: string | null
          current_place_since?: string | null
          description?: string | null
          embedding?: string | null
          estimated_value?: number | null
          household_id: string
          id?: string
          last_moved_by?: string | null
          metadata?: Json
          name: string
          photo_urls?: string[]
          product_link?: string | null
          product_links?: string[]
          qr_token?: string | null
          quantity?: number
          tags?: string[]
          updated_at?: string
          value_currency?: string | null
          value_source?: string | null
          value_updated_at?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          current_place_id?: string | null
          current_place_since?: string | null
          description?: string | null
          embedding?: string | null
          estimated_value?: number | null
          household_id?: string
          id?: string
          last_moved_by?: string | null
          metadata?: Json
          name?: string
          photo_urls?: string[]
          product_link?: string | null
          product_links?: string[]
          qr_token?: string | null
          quantity?: number
          tags?: string[]
          updated_at?: string
          value_currency?: string | null
          value_source?: string | null
          value_updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'items_current_place_id_fkey'
            columns: ['current_place_id']
            isOneToOne: false
            referencedRelation: 'places'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'items_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
        ]
      }
      places: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          household_id: string
          id: string
          item_id: string | null
          name: string
          parent_place_id: string | null
          photo_url: string | null
          photo_urls: string[]
          qr_token: string | null
          tags: string[]
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          household_id: string
          id?: string
          item_id?: string | null
          name: string
          parent_place_id?: string | null
          photo_url?: string | null
          photo_urls?: string[]
          qr_token?: string | null
          tags?: string[]
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          household_id?: string
          id?: string
          item_id?: string | null
          name?: string
          parent_place_id?: string | null
          photo_url?: string | null
          photo_urls?: string[]
          qr_token?: string | null
          tags?: string[]
        }
        Relationships: [
          {
            foreignKeyName: 'places_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'places_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'places_parent_place_id_fkey'
            columns: ['parent_place_id']
            isOneToOne: false
            referencedRelation: 'places'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          default_language: Database['public']['Enums']['supported_language'] | null
          display_name: string | null
          id: string
          voice_provider: Database['public']['Enums']['voice_provider'] | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          default_language?: Database['public']['Enums']['supported_language'] | null
          display_name?: string | null
          id: string
          voice_provider?: Database['public']['Enums']['voice_provider'] | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          default_language?: Database['public']['Enums']['supported_language'] | null
          display_name?: string | null
          id?: string
          voice_provider?: Database['public']['Enums']['voice_provider'] | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_household_member: { Args: { _household_id: string }; Returns: boolean }
      is_household_owner: { Args: { _household_id: string }; Returns: boolean }
      convert_item_to_place: {
        Args: { _item_id: string; _user_id: string }
        Returns: string
      }
      place_would_cycle: {
        Args: { _new_parent: string; _place_id: string }
        Returns: boolean
      }
      resolve_code: {
        Args: { _code_value: string; _user_id: string }
        Returns: {
          entity_id: string
          entity_type: Database['public']['Enums']['external_entity_type']
          household_id: string
        }[]
      }
    }
    Enums: {
      external_code_type:
        | 'qr'
        | 'code128'
        | 'code39'
        | 'code93'
        | 'ean13'
        | 'ean8'
        | 'upc_a'
        | 'upc_e'
        | 'codabar'
        | 'itf'
        | 'data_matrix'
        | 'pdf417'
        | 'aztec'
        | 'other'
      external_entity_type: 'item' | 'place'
      household_role: 'owner' | 'member'
      supported_language: 'en' | 'vi'
      voice_provider: 'on-device' | 'whisper'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      external_code_type: [
        'qr',
        'code128',
        'code39',
        'code93',
        'ean13',
        'ean8',
        'upc_a',
        'upc_e',
        'codabar',
        'itf',
        'data_matrix',
        'pdf417',
        'aztec',
        'other',
      ],
      external_entity_type: ['item', 'place'],
      household_role: ['owner', 'member'],
      supported_language: ['en', 'vi'],
      voice_provider: ['on-device', 'whisper'],
    },
  },
} as const
