const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Wires a real release keystore into the generated `android/` project.
 *
 * `android/` is gitignored (regenerated by `expo prebuild`), so the signing
 * config has to live here to survive. Credentials are read at build time from
 * `keystore.properties` at the repo root — also gitignored, never committed.
 * If that file is missing the build falls back to the debug keystore, so a
 * fresh clone still builds.
 */

// Anchors from the Expo/RN `android/app/build.gradle` template. If an SDK
// upgrade rewrites them, `applyReleaseSigning` throws rather than silently
// producing a debug-signed release APK.
const SIGNING_CONFIGS_ANCHOR = '    signingConfigs {\n        debug {';

const RELEASE_SIGNING_CONFIG = `    signingConfigs {
        release {
            def keystorePropsFile = rootProject.file('../keystore.properties')
            if (keystorePropsFile.exists()) {
                def keystoreProps = new Properties()
                keystorePropsFile.withInputStream { keystoreProps.load(it) }
                storeFile rootProject.file('../' + keystoreProps['STUFFSEARCH_UPLOAD_STORE_FILE'])
                storePassword keystoreProps['STUFFSEARCH_UPLOAD_STORE_PASSWORD']
                keyAlias keystoreProps['STUFFSEARCH_UPLOAD_KEY_ALIAS']
                keyPassword keystoreProps['STUFFSEARCH_UPLOAD_KEY_PASSWORD']
            }
        }
        debug {`;

// The `debug` build type carries an identical `signingConfig signingConfigs.debug`
// line, so the surrounding comment is what makes this anchor unambiguous.
const RELEASE_BUILD_TYPE_ANCHOR =
  '            // Caution! In production, you need to generate your own keystore file.\n' +
  '            // see https://reactnative.dev/docs/signed-apk-android.\n' +
  '            signingConfig signingConfigs.debug';

const RELEASE_BUILD_TYPE =
  "            signingConfig rootProject.file('../keystore.properties').exists() ? signingConfigs.release : signingConfigs.debug";

const APPLIED_MARKER = 'STUFFSEARCH_UPLOAD_STORE_FILE';

/**
 * Pure transform over the contents of `android/app/build.gradle`.
 * Idempotent: returns the input unchanged if already applied.
 */
function applyReleaseSigning(gradle) {
  if (gradle.includes(APPLIED_MARKER)) {
    return gradle;
  }

  if (!gradle.includes(SIGNING_CONFIGS_ANCHOR)) {
    throw new Error(
      'withAndroidReleaseSigning: unexpected app/build.gradle template — signingConfigs block not found.'
    );
  }
  if (!gradle.includes(RELEASE_BUILD_TYPE_ANCHOR)) {
    throw new Error(
      'withAndroidReleaseSigning: unexpected app/build.gradle template — release signingConfig not found.'
    );
  }

  return gradle
    .replace(SIGNING_CONFIGS_ANCHOR, RELEASE_SIGNING_CONFIG)
    .replace(RELEASE_BUILD_TYPE_ANCHOR, RELEASE_BUILD_TYPE);
}

function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    cfg.modResults.contents = applyReleaseSigning(cfg.modResults.contents);
    return cfg;
  });
}

module.exports = withAndroidReleaseSigning;
module.exports.applyReleaseSigning = applyReleaseSigning;
